config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users, only:[:index, :show, :edit, :update] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end
  
  resources :posts do
    resources :comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
    collection do
      get 'confirm'
    end
  end

  root :to => 'homes#top' 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  # Defines the root path route ("/")
  # root "posts#index"
  # get 'top' => 'homes#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post

    validates :comment, presence: true, length: { maximum: 35 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  attachment :image
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :location, presence: true, length: { maximum: 15 }
  validates :text, presence: true, length: { maximum: 195 }
  validates :image, presence: true

  enum status: { published: 0, draft: 1 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy 
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  attachment :profile_image

  validates :name, presence: true

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:top] 
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(resource)
      posts_path
  end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        post = Post.find(params[:post_id])
        @comment = current_user.comments.new(comment_params)
        @comment.post_id = post.id
        if @comment.save
            redirect_to post_path(post)
        else
            @post = Post.find(params[:post_id])
            @comments = @post.comments.page(params[:page]).per(7).reverse_order
            render 'posts/show', status: :unprocessable_entity
        end
    end
    
    def destroy
        Comment.find_by(id: params[:id], post_id: params[:post_id]).destroy
        redirect_to post_path(params[:post_id])
    end
    
    private
    def comment_params
        params.require(:comment).permit(:comment)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
        post = Post.find(params[:post_id])
        favorite = current_user.favorites.new(post_id: post.id)
        favorite.save
        redirect_to post_path(post)
    end
      
    def destroy
        post = Post.find(params[:post_id])
        favorite = current_user.favorites.find_by(post_id: post.id)
        favorite.destroy
        redirect_to post_path(post)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @posts = Post.published.page(params[:page]).reverse_order
    @posts = @posts.where('location LIKE ?', "%#{params[:search]}%") if params[:search].present?
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.page(params[:page]).per(7).reverse_order
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  def confirm
    @posts = current_user.posts.draft.page(params[:page]).reverse_order
  end

  private
  def post_params
    params.require(:post).permit(:user_id, :location, :text, :image, :status)
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    def create
        current_user.follow(params[:user_id])
        redirect_to request.referer
    end
      
    def destroy
        current_user.unfollow(params[:user_id])
        redirect_to request.referer
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).per(5).reverse_order
  end
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(8).reverse_order
    @following_users = @user.following_user
    @follower_users = @user.follower_user
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def follows
    user = User.find(params[:id])
    @users = user.following_user.page(params[:page]).per(3).reverse_order
  end
  
  def followers
    user = User.find(params[:id])
    @users = user.follower_user.page(params[:page]).per(3).reverse_order
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<div class="cover align-middle">
  <div class="text-center">
    <p class="sub-title">〜旅行の思い出を共有する〜</p>
    <h1 class="title mb-2">Traveler</h1>
    <%= link_to new_user_registration_path do %>
    <h2 class="btn btn-primary mr-2">新規登録</h2>
    <% end %>
    <%= link_to new_user_session_path do %>
      <h2 class="btn btn-success ml-2">ログイン</h2>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Traveler</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %> 
      <header>
        <div><%= link_to root_path, class: "text-white nav-link" do %>traveler<% end %></div>
        <div><%= link_to "トップ", root_path, class: "text-white nav-link" %></div>
        <div><%= link_to "投稿する", new_post_path, class: "text-white nav-link" %></div>
        <div><%= link_to "投稿一覧", posts_path, class: "text-white nav-link" %></div>
        <div><%= link_to "下書き一覧", confirm_posts_path, class: "text-white nav-link" %></div>
        <div><%= link_to "ユーザ一覧", users_path, class: "text-white nav-link" %></div>
        <div><%= link_to "マイページ", user_path(current_user.id), class: "text-white nav-link" %></div>
        <div><%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: "text-white nav-link" %></div>
      </header>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_index.html.erb
<div class="row mt-3 mb-3 align-self-end">
  <%= form_with method: :get, local: true do |f| %>
  <%= f.text_field :search %>
  <%= f.submit '検索する', name: nil %>
  <% end %>
</div>
<div class="row mt-5 index-left w-100">
  <% posts.each do |post| %>
  <div class="one-post col-sm-4 mb-3">
    <%= link_to post_path(post) do %>
    <p class="caption"><%= post.user.name %></p>
    <%= attachment_image_tag post, :image, format: 'jpeg', size: '300x200' %>
    <p class="caption"><%= post.location %></p>
    <p class="caption"><%= "#{post.comments.count} コメント" %></p>
    <% end %>
  </div>
  <% end %>
</div>
<%= paginate posts %>

app/views/posts/confirm.html.erb
<div class="cover-index">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">下書き一覧</h1>
    </div>
    <%= render 'index', posts: @posts %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="cover-edit">
  <div class="container">
    <div class="row">
      <h1 class="font-weight-normal mt-5 mb-5">旅行投稿編集</h1>
    </div>
    <% if @post.errors.any? %>
    <div class="card text-center card text-white bg-danger mb-3">
      <%= @post.errors.count %>件のエラーが発生しました
      <% @post.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
      </div>
    <% end %>
    <div class="row">
      <%= form_with model: @post, local:true do |f| %>
      <div class="form-group mb-3">
        <label class="form-label">旅行先</label>
        <%= f.text_field :location, class: "form-control" %>
      </div>
      <div class="form-group mb-3">
        <label class="form-label">感想</label>
        <%=f.text_area :text, rows: 10, class: "form-control" %>
      </div>
      <div class="form-group mb-4">
        <label class="form-label">画像</label><br>
        <%= f.file_field :image %>
      </div>
      <div class="form-group">
        <%= f.select :status, Post.statuses.keys.map { |k| [t("enums.post.status.#{k}"),k]}, {}, {class: "custom-select w-25 mb-3"} %>
      </div>
      <%= f.submit '保存する', class: "btn btn-success" %><br>
      <%= link_to '投稿詳細ページへ', post_path(@post), class: "btn btn-dark mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="cover-index">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">旅行投稿一覧</h1>
    </div>
    <%= render 'index', posts: @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="cover-new">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">旅行新規投稿</h1>
    </div>
    <% if @post.errors.any? %>
    <div class="card text-center card text-white bg-danger mt-3">
      <%= @post.errors.count %>件のエラーが発生しました
      <% @post.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
      </div>
    <% end %>
    <div class="row mt-5">
      <%= form_with model: @post, local:true do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <div class="form-group mb-3">
        <label class="form-label">【旅行先】</label>
        <%= f.text_field :location, class: "form-control" %>
      </div>
      <div class="form-group mb-3">
        <label class="form-label">【感想】</label>
        <%=f.text_area :text, rows: 10, class: "form-control" %>
      </div>
      <div class="form-group mb-3">
        <label class="form-label">【画像】</label><br>
        <%= f.file_field :image %>
      </div>
      <div class="form-group">
        <%= f.select :status, Post.statuses.keys.map { |k| [t("enums.post.status.#{k}"),k]}, {}, {class: "custom-select w-25 mb-3"} %>
      </div>
      <%= f.submit '投稿する', class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="cover-show">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">旅行投稿詳細</h1>
    </div>
    <% if @comment.errors.any? %>
    <div class="card text-center card text-white bg-danger mt-3">
      <%= @comment.errors.count %>件のエラーが発生しました
      <% @comment.errors.full_messages.each do |message| %>
       <%= message %>
      <% end %>
    </div>
    <% end %>
    <div class="d-flex mt-5">
      <div class="d-block">
        <p class="caption"><%= @post.user.name %></p>
        <%= attachment_image_tag @post, :image, format: 'jpeg', size: "450x350" %><br>
        <p class="caption"><%= @post.location %>
          <% if @post.favorited_by?(current_user) %>
          <%= link_to post_favorites_path(@post),  data: { turbo_method: :delete }, class: "favorite_btn" do %>
          ♥<%= @post.favorites.count %> いいね
          <% end %>
          <% else %>
          <%= link_to post_favorites_path(@post),  data: { turbo_method: :post }, class: "favorite_btn" do %>
            ♡<%= @post.favorites.count %> いいね
          <% end %>
          <% end %>
        </p>
        <h2>感想</h2>
        <p id="text"><%= @post.text %></p>
        <% if @post.user == current_user %>
          <%= link_to '編集する', edit_post_path(@post.id), class: "btn btn-info mr-3" %>
          <%= link_to '削除する', post_path(@post.id),  data: { turbo_method: :delete, turbo_confirm:  "本当に消しますか？"}, class: "btn btn-danger" %><br>
        <% end %>
        <%= link_to '投稿一覧ページへ', posts_path, class: "btn btn-dark mt-3" %>
      </div>
      <div class="comments ml-5 mt-5">
        <%= form_with(model:[@post, @comment], local: true) do |f| %>
        <%= f.text_area :comment, :size=>"60x3",placeholder: "コメントする" %>
        <%= f.submit "送信する", class: "btn btn-success mb-4" %>
        <% end %>
        <p>コメント件数：<%= @comments.count %></p>
          <% @comments.each do |comment| %>
        <div class="comments-index mb-2">
          <%= comment.user.name %>
          <%= comment.created_at.strftime('%Y/%m/%d') %><br>
          <div class="d-flex">
            <%= comment.comment %>
            <% if comment.user == current_user %>
            <div class="comment-delete">
              <%= link_to "削除", post_comment_path(comment.post, comment),  data: { turbo_method: :delete }, class: "btn-sm btn-danger" %>
            </div>
          </div>
        </div>
        <% end %>
        <% end %>
        <%= paginate @comments %>
      </div>
    </div>
  </div>
</div>

app/views/users/_index.html.erb
<div class="row mt-5 w-50">
<% users.each do |user| %>
<div class="one-post card mt-3">
  <%= link_to user_path(user) do %>
  <div class="d-flex">
    <%= attachment_image_tag user, :profile_image, size: '50x50', fallback: "no_image.svg", class: "mt-3 profile-img" %>
    <p class="caption h4 mt-4"><%= user.name %></p>
  </div>
  <p class="caption"><%= "#{user.posts.count} 投稿" %></p>
  <% end %>
</div>
<% end %>
</div>
<%= paginate users %>

app/views/users/edit.html.erb
<div class="cover-user-edit">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">プロフィール編集</h1>
    </div>
    <div class="row mt-5">
      <%= form_with model: @user, local:true do |f| %>
      <div class="form-group">
        <label class="form-label">名前</label>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class: "form-control" %>
      </div>
      <div class="form-group mt-3">
        <label class="form-label">プロフィール画像</label><br>
        <%= attachment_image_tag @user, :profile_image, size: '100x100', fallback: "no_image.svg", class: "mb-3 profile-img" %><br>
        <%= f.file_field :profile_image %>
      </div>
      <div class="form-group mt-3">
        <label class="form-label">プロフィール</label>
        <%= f.text_field :profile, class: "form-control" %><br>
      </div>
      <%= f.submit '保存する', class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="cover-user-index">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">フォロワー一覧</h1>
    </div>
    <%= render 'index', users: @users, user: @user %>
  </div>
</div>

app/views/users/follows.html.erb
<div class="cover-user-index">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">フォロー一覧</h1>
    </div>
    <%= render 'index', users: @users, user: @user %>
  </div>
</div>

app/views/users/index.html.erb
<div class="cover-user-index">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">ユーザ一覧</h1>
    </div>
    <%= render 'index', users: @users, user: @user %>
  </div>
</div>

app/views/users/show.html.erb
<div class="cover-user-show">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <% if user_signed_in? && @user == current_user %>
        <h1 class="font-weight-normal">マイページ</h1>
      <% else %>
        <h1 class="font-weight-normal"><%= @user.name %>さんのページ</h1>
      <% end %>
    </div>
    <% if user_signed_in? && @user == current_user %>
      <p class="d-flex align-self-end">
        <%= link_to "プロフィール編集", edit_user_path(@user), class: "btn btn-success" %>
      </p>
    <% end %>
    <% if current_user != @user %>
      <% if current_user.following?(@user) %>
        <p class="d-flex align-self-end">
          <%= link_to 'フォロー外す', user_relationships_path(@user.id),  data: { turbo_method: :delete }, class: "btn btn-danger" %>
        </p>
        <% else %>
        <p class="d-flex align-self-end">
          <%= link_to 'フォローする', user_relationships_path(@user.id),  data: { turbo_method: :post }, class:"btn btn-success" %>
        </p>
      <% end %>
    <% end %>
    <div class="d-flex w-100">
      <%= attachment_image_tag @user, :profile_image, size: '100x100', fallback: "no_image.svg", class: "mb-3 profile-img" %>
      <h4 class="ml-3 mb-3 card w-100 profile"><%= @user.profile %></h4>
    </div>
    <div class="d-flex">
      <%= link_to follows_user_path(@user) do %>
        <h6>フォロー<%= @following_users.count %></h6>
      <% end %>&nbsp;&nbsp;
      <%= link_to followers_user_path(@user) do %>
        <h6>フォロワー<%= @follower_users.count %></h6>
      <% end %>
    </div>
    <div class="row mt-5 index-left w-100">
      <% @posts.each do |post| %>
        <div class="one-post col-sm-3 mb-3">
          <%= link_to post_path(post) do %>
            <%= attachment_image_tag post, :image, format: 'jpeg', size: '200x133' %>
            <p class="caption mb-0"><%= post.location %></p>
            <p class="caption"><%= "#{post.comments.count} コメント" %></p>
          <% end %>
        </div>
      <% end %>
    </div>
    <%= paginate @posts %>
  </div>
</div>